name: Reversi
version: 0.31.0
synopsis: The game of Reversi written in Haskell.
description: A fun, simple board game to play with family and friends.
maintainer: Rashad Gover <rashad.sasaki@gmail.com>
github: https://github.com/rashadg1030
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - containers
  - random

executable:
  main: Main.hs
  source-dirs: src
  other-modules:
    - Actions
    - Board
    - Types

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - tests
      - src
    other-modules:
      - Actions
      - Board
      - Types
      - ActionsSpec
    dependencies:
      - hspec == 2.*
    build-tools: hspec-discover
