name: reversi
version: 0.31.0
synopsis: The game of Reversi written in Haskell.
description: A fun, simple board game to play with family and friends.
maintainer: Rashad Gover <rashad.sasaki@gmail.com>
github: https://github.com/rashadg1030
category: Experimental

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - containers
  - random
  - mtl
  - transformers
  - pretty-simple

default-extensions:
  - GeneralizedNewtypeDeriving
  - NamedFieldPuns
  - TupleSections
  - FlexibleContexts
  - FlexibleInstances 
  - InstanceSigs
  - TypeSynonymInstances

library:
  exposed-modules:
    - Reversi.Actions
    - Reversi.Board
    - Reversi.GameTree
    - Reversi.Heuristic
    - Reversi.Types
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: src
  other-modules:
    - Reversi.Actions
    - Reversi.Board
    - Reversi.Types
    - Reversi.GameTree
    - Reversi.Heuristic

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - tests
      - src
    other-modules:
      - Reversi.Actions
      - Reversi.Board
      - Reversi.Types
      - Reversi.ActionsSpec
    dependencies:
      - hspec == 2.*
    build-tools: hspec-discover
