name: Reversi
version: 0.31.0
synopsis: The game of Reversi written in Haskell.
description: A fun, simple board game to play with family and friends.
maintainer: Rashad Gover <rashad.sasaki@gmail.com>
github: https://github.com/rashadg1030
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - map

library:
  source-dirs: src
  exposed-modules:
    - Hpack
    - Hpack.Config
    - Hpack.Render
    - Hpack.Yaml

executable:
  main: Main.hs
  source-dirs: src
  dependencies:
    - Actions
    - Board
    - Types

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - hspec == 2.*
    build-tools: hspec-discover
